### PR TITLE
#28: Support older gcc and Linux headers

### LINKED ISSUE #28: Can't build project
Hi!
I can't compile project on CentOS release 6.6
g++ version:

```
g++ -v
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-18) (GCC)
```
error:
```
g++ -O2 -I/opt/jdk/jdk1.7.0_75//include -I/opt/jdk/jdk1.7.0_75//include/linux -fPIC -shared -o build/libasyncProfiler.so src/*.cpp -ldl -lpthread
In file included from src/profiler.h:22,
                 from src/javaApi.cpp:18:
src/spinLock.h: In member function ‘void SpinLock::spinLock()’:
src/spinLock.h:39: error: ‘__builtin_ia32_pause’ was not declared in this scope
In file included from src/perfEvent.h:23,
                 from src/perfEvent.cpp:25:
src/spinLock.h: In member function ‘void SpinLock::spinLock()’:
src/spinLock.h:39: error: ‘__builtin_ia32_pause’ was not declared in this scope
In file included from src/profiler.h:22,
                 from src/profiler.cpp:24:
src/spinLock.h: In member function ‘void SpinLock::spinLock()’:
src/spinLock.h:39: error: ‘__builtin_ia32_pause’ was not declared in this scope
In file included from src/profiler.h:22,
                 from src/vmEntry.cpp:22:
src/spinLock.h: In member function ‘void SpinLock::spinLock()’:
src/spinLock.h:39: error: ‘__builtin_ia32_pause’ was not declared in this scope
make: *** [build/libasyncProfiler.so] Error 1
```

### PR DESCRIPTION
**Pull request by apangin**
Resolves #28

Fixed compiler errors encountered on older systems:
- '__builtin_ia32_pause' was not declared in this scope
- 'SYS_perf_event_open' was not declared in this scope
- aggregate 'f_owner_ex ex' has incomplete type and cannot be defined
- 'F_OWNER_TID' was not declared in this scope
- 'F_SETOWN_EX' was not declared in this scope
- 'NT_GNU_BUILD_ID' was not declared in this scope

Tested on Linux 2.6.39, gcc 4.1.2, JDK 6u26

### CODE REVIEW

File: src/symbols.cpp [hunk 1]
```diff
@@ -148,7 +148,7 @@ bool ElfParser::loadSymbolsUsingBuildId() {
     }
 
     ElfNote* note = (ElfNote*)at(section);
-    if (note->n_namesz != 4 || note->n_descsz < 2 || note->n_descsz > 64 || note->n_type != NT_GNU_BUILD_ID) {
+    if (note->n_namesz != 4 || note->n_descsz < 2 || note->n_descsz > 64) {
```
Comment (goldshtn) [inline src/symbols.cpp]: Why has this test been removed?

Comment (apangin) [inline src/symbols.cpp]: When I tested various Linux distributions and gcc versions I've found that NT_GNU_BUILD_ID is not always defined in <elf.h>. Well, I could define it myself, but the check seems redundant, because the section here is known to be SHT_NOTE with the name ".note.gnu.build-id".
